AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The imgn serverless app
Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    BinaryMediaTypes:
      - image~1jpeg
      - image~1png
Resources:
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: uploadimg/
      Handler: uploadimg
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - s3:PutObject
              Resource: 'arn:aws:s3:::imgn-gallery/*'
  ListImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: listimgs/
      Handler: listimgs
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /gallery
            Method: GET
Outputs:
  ImgnAPIEndpoint:
    Description: "Imgn HTTP API Gateway endpoint URL for Prod env"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
